apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: test-goapp
  name: test-goapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/instance: test-goapp
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: test-goapp
    spec:
      containers:
      - env:
        - name: GOMEMLIMIT
          valueFrom:
            resourceFieldRef:
              divisor: "0"
              resource: limits.memory
        - name: GOMAXPROCS
          valueFrom:
            resourceFieldRef:
              divisor: "0"
              resource: limits.cpu
        - name: ENV
          value: dev
        - name: LOGGER_TYPE
          value: production
        - name: REGION
          value: us-central1
        image: us-central1-docker.pkg.dev/docker-repository/test-goapp/test-goapp:recent-gitsha
        imagePullPolicy: IfNotPresent
        name: test-goapp
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: "1"
            memory: 768Mi
          requests:
            cpu: 300m
            memory: 512Mi
      dnsPolicy: ClusterFirst
      securityContext:
        fsGroup: 1000
      terminationGracePeriodSeconds: 15
